/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CommandCenterRouteImport } from './routes/command-center'
import { Route as DigitalTwinRouteImport } from './routes/digital-twin'
import { Route as IncidentsRouteImport } from './routes/incidents'
import { Route as InfrastructureRouteImport } from './routes/infrastructure'
import { Route as PredictionsRouteImport } from './routes/predictions'
import { Route as SimulatorRouteImport } from './routes/simulator'
import { Route as VideoAnalysisRouteImport } from './routes/video-analysis'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandCenterRoute = CommandCenterRouteImport.update({
  id: '/command-center',
  path: '/command-center',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalTwinRoute = DigitalTwinRouteImport.update({
  id: '/digital-twin',
  path: '/digital-twin',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsRoute = IncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const InfrastructureRoute = InfrastructureRouteImport.update({
  id: '/infrastructure',
  path: '/infrastructure',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictionsRoute = PredictionsRouteImport.update({
  id: '/predictions',
  path: '/predictions',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulatorRoute = SimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoAnalysisRoute = VideoAnalysisRouteImport.update({
  id: '/video-analysis',
  path: '/video-analysis',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/command-center': typeof CommandCenterRoute
  '/digital-twin': typeof DigitalTwinRoute
  '/incidents': typeof IncidentsRoute
  '/infrastructure': typeof InfrastructureRoute
  '/predictions': typeof PredictionsRoute
  '/simulator': typeof SimulatorRoute
  '/video-analysis': typeof VideoAnalysisRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/command-center': typeof CommandCenterRoute
  '/digital-twin': typeof DigitalTwinRoute
  '/incidents': typeof IncidentsRoute
  '/infrastructure': typeof InfrastructureRoute
  '/predictions': typeof PredictionsRoute
  '/simulator': typeof SimulatorRoute
  '/video-analysis': typeof VideoAnalysisRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/command-center': typeof CommandCenterRoute
  '/digital-twin': typeof DigitalTwinRoute
  '/incidents': typeof IncidentsRoute
  '/infrastructure': typeof InfrastructureRoute
  '/predictions': typeof PredictionsRoute
  '/simulator': typeof SimulatorRoute
  '/video-analysis': typeof VideoAnalysisRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/command-center'
    | '/digital-twin'
    | '/incidents'
    | '/infrastructure'
    | '/predictions'
    | '/simulator'
    | '/video-analysis'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/command-center'
    | '/digital-twin'
    | '/incidents'
    | '/infrastructure'
    | '/predictions'
    | '/simulator'
    | '/video-analysis'
  id:
    | '__root__'
    | '/'
    | '/command-center'
    | '/digital-twin'
    | '/incidents'
    | '/infrastructure'
    | '/predictions'
    | '/simulator'
    | '/video-analysis'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommandCenterRoute: typeof CommandCenterRoute
  DigitalTwinRoute: typeof DigitalTwinRoute
  IncidentsRoute: typeof IncidentsRoute
  InfrastructureRoute: typeof InfrastructureRoute
  PredictionsRoute: typeof PredictionsRoute
  SimulatorRoute: typeof SimulatorRoute
  VideoAnalysisRoute: typeof VideoAnalysisRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command-center': {
      id: '/command-center'
      path: '/command-center'
      fullPath: '/command-center'
      preLoaderRoute: typeof CommandCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital-twin': {
      id: '/digital-twin'
      path: '/digital-twin'
      fullPath: '/digital-twin'
      preLoaderRoute: typeof DigitalTwinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents': {
      id: '/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof IncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infrastructure': {
      id: '/infrastructure'
      path: '/infrastructure'
      fullPath: '/infrastructure'
      preLoaderRoute: typeof InfrastructureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predictions': {
      id: '/predictions'
      path: '/predictions'
      fullPath: '/predictions'
      preLoaderRoute: typeof PredictionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulator': {
      id: '/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof SimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video-analysis': {
      id: '/video-analysis'
      path: '/video-analysis'
      fullPath: '/video-analysis'
      preLoaderRoute: typeof VideoAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommandCenterRoute: CommandCenterRoute,
  DigitalTwinRoute: DigitalTwinRoute,
  IncidentsRoute: IncidentsRoute,
  InfrastructureRoute: InfrastructureRoute,
  PredictionsRoute: PredictionsRoute,
  SimulatorRoute: SimulatorRoute,
  VideoAnalysisRoute: VideoAnalysisRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
